{
  "iceskating": [
      {
        "Prop_ID": "B169",
        "Name": "Abe Stark Rink",
        "Location": "Coney Island Boardwalk and West 19th Street",
        "Phone": "(718) 946-6536",
        "Accessible": "Y",
        "lat": "40.5731",
        "lon": "-73.9859",
        "IceSkating_Type": "Indoor",
        "Public_Skate_Admission_Price_Adult": "$10.00",
        "Public_Skate_Admission_Price_Child": "$10.00",
        "Public_Skate_Admission_Price_Senior": "$10.00",
        "Skate_Rental_Cost": "$5.00",
        "Opening_Date": "2016-11-05",
        "Sunday_Public_Skating_Hours": "1:00 p.m.- 2:30 p.m.",
        "Saturday_Public_Skating_Hours": "1:00 p.m.- 2:30 p.m.",
        "Notes": "Open weekends only. All information subject to change; please call ahead for details.  All skaters must sign a Risk of Ice Skating/Hockey Activity Agreement. Persons under 18 years of age must have written consent form signed by parent or guardian. Agreement forms available at rink. A parent must sign the agreement form in the presence of a rink employee or parent's signature must be notarized."
      },
      {
        "Prop_ID": "B073",
        "Name": "LeFrak Center at Lakeside",
        "Location": "Enter at Lincoln Road and Ocean Avenue.",
        "Phone": "(718) 462-0010",
        "Accessible": "N",
        "lat": "40.6579",
        "lon": "-73.9653",
        "IceSkating_Type": "Outdoor",
        "Public_Skate_Admission_Price_Adult": "$6; $9 on weekends. Weekend pricing begins on Fridays at 4:00 p.m.",
        "Public_Skate_Admission_Price_Child": "$6; $9 on weekends. Weekend pricing begins on Fridays at 4:00 p.m.",
        "Skate_Rental_Cost": "$6",
        "Opening_Date": "2016-10-28",
        "Closing_Date": "2017-03-26",
        "Sunday_Public_Skating_Hours": "11:30 a.m. - 5:15 p.m.",
        "Monday_Public_Skating_Hours": "9:00 a.m. - 5:15 p.m.",
        "Tuesday_Public_Skating_Hours": "9:00 a.m. - 5:15 p.m.",
        "Wednesday_Public_Skating_Hours": "9:00 a.m. - 5:15 p.m.",
        "Thursday_Public_Skating_Hours": "9:00 a.m. - 5:15 p.m.",
        "Friday_Public_Skating_Hours": "9:00 a.m. - 9:00 p.m.",
        "Saturday_Public_Skating_Hours": "11:30 a.m. - 9:00 p.m.",
        "Notes": "The facility, including rinks, snack bar and Bluestone CafÉ, may be utilized at other times for special events, private functions, classes or programmed activities, and/or rink rentals."
      },
      {
        "Prop_ID": "M008",
        "Name": "The Rink at Bryant Park",
        "Location": "Between 40th and 42nd Streets",
        "Phone": "(917) 438-5166",
        "Accessible": "Y",
        "lat": "40.7536",
        "lon": "-73.9848",
        "IceSkating_Type": "Outdoor",
        "Public_Skate_Admission_Price_Adult": "Free",
        "Public_Skate_Admission_Price_Child": "Free",
        "Public_Skate_Admission_Price_Senior": "Free",
        "Skate_Rental_Cost": "$20. The Rink at Bryant Park provides skate aids for $20/hour.",
        "Locker_Information": "Lockers are free, but locks cost $10.<br />Bag check is $10.00. ($12.00 for large bags)",
        "Opening_Date": "2016-10-29",
        "Closing_Date": "2017-03-05",
        "Sunday_Public_Skating_Hours": "8:00 a.m. - 10:00 p.m.",
        "Monday_Public_Skating_Hours": "8:00 a.m. - 10:00 p.m.",
        "Tuesday_Public_Skating_Hours": "8:00 a.m. - 10:00 p.m.",
        "Wednesday_Public_Skating_Hours": "8:00 a.m. - 10:00 p.m.",
        "Thursday_Public_Skating_Hours": "8:00 a.m. - 10:00 p.m.",
        "Friday_Public_Skating_Hours": "8:00 a.m. - 10:00 p.m.",
        "Saturday_Public_Skating_Hours": "8:00 a.m. - 10:00 p.m.",
        "Programming": "Skating lessons are available."
      },
      {
        "Prop_ID": "M010",
        "Name": "Lasker Rink",
        "Location": "Entrance just south of park entrance at 110th Street & Lenox Avenue",
        "Phone": "(917) 492-3856",
        "Accessible": "Y",
        "lat": "40.7964",
        "lon": "-73.9546",
        "IceSkating_Type": "Outdoor",
        "Public_Skate_Admission_Price_Adult": "$8",
        "Public_Skate_Admission_Price_Child": "$4.00",
        "Public_Skate_Admission_Price_Senior": "$2.25",
        "Skate_Rental_Cost": "$7 (tax included)",
        "Locker_Information": "$3.25 + $4.00 deposit for lock<br> (Deposit will be returned to the customer upon return of the lock.)",
        "Opening_Date": "2016-10-29",
        "Closing_Date": "2017-03-19",
        "Sunday_Public_Skating_Hours": "12:30 p.m. - 4:30 p.m.",
        "Monday_Public_Skating_Hours": "10:00 a.m. - 4:00 p.m.",
        "Tuesday_Public_Skating_Hours": "10:00 a.m. - 4:00 p.m.",
        "Wednesday_Public_Skating_Hours": "10:00 a.m. - 4:00 p.m.",
        "Thursday_Public_Skating_Hours": "10:00 a.m. - 4:00 p.m.",
        "Friday_Public_Skating_Hours": "10:00 a.m. - 4:50 p.m.; 6:00 p.m. to 11:00 p.m.",
        "Saturday_Public_Skating_Hours": "1:00 p.m. - 11:00 p.m.",
        "Programming": "Adult hockey, youth hockey, open hockey, hockey classes, Learn to Skate, Learn to Skate Holiday Camp, private & semi-private lessons, birthday parties. Adult Open Hockey every Saturday night from 9:15 pm - 10:45 p.m.; $15 admission, free for goalies.",
        "Notes": "Check <a href =\"http://www.laskerrink.com/\">laskerrink.com</a> for more information6"
      },
      {
        "Prop_ID": "M010",
        "Name": "Wollman Rink",
        "Location": "Central Park at 63rd Street",
        "Phone": "(212) 439-6900",
        "Accessible": "N",
        "lat": "40.7677",
        "lon": "-73.9744",
        "IceSkating_Type": "Outdoor",
        "Public_Skate_Admission_Price_Adult": "$12 Mon.-Thurs.; $19.00 Fri.-Sun. and holidays<br>",
        "Public_Skate_Admission_Price_Child": "(11 and under) $6.00<br>",
        "Public_Skate_Admission_Price_Senior": "$5.00 Mon.-Thurs.; $9.00 Fri.-Sun. and holidays<br>",
        "Skate_Rental_Cost": "$9.00 (tax included)",
        "Locker_Information": "$5.00 + $6.00 deposit<br>(Deposit will be returned to the customer after lock is returned.)",
        "Opening_Date": "2016-10-23",
        "Closing_Date": "2017-04-02",
        "Sunday_Public_Skating_Hours": "10:00 a.m. - 9:00 p.m.",
        "Monday_Public_Skating_Hours": "10:00 a.m. - 2:30 p.m.",
        "Tuesday_Public_Skating_Hours": "10:00 a.m. - 2:30 p.m.",
        "Wednesday_Public_Skating_Hours": "10:00 a.m. - 10:00 p.m.",
        "Thursday_Public_Skating_Hours": "10:00 a.m. - 10:00 p.m.",
        "Friday_Public_Skating_Hours": "10:00 a.m. - 11:00 p.m.",
        "Saturday_Public_Skating_Hours": "10:00 a.m. - 11:00 p.m.",
        "Notes": "Cash only. Spectator Fee: $5.00."
      },
      {
        "Prop_ID": "R005",
        "Name": "WWII Veterans War Memorial Ice Skating Rink",
        "Location": "Victory Blvd., west of Clove Rd.",
        "Phone": "(718) 720-1010",
        "Accessible": "N",
        "lat": "40.6156",
        "lon": "-74.1077",
        "IceSkating_Type": "Indoor",
        "Public_Skate_Admission_Price_Adult": "$10.00",
        "Public_Skate_Admission_Price_Child": "$10.00",
        "Public_Skate_Admission_Price_Senior": "$10.00",
        "Skate_Rental_Cost": "$5.00",
        "Closing_Date": "2017-04-09",
        "Sunday_Public_Skating_Hours": "Noon - 8:00 p.m.",
        "Friday_Public_Skating_Hours": "4:00 p.m - 11:00 p.m.",
        "Saturday_Public_Skating_Hours": "Noon - 4:30 p.m. and 7:00 p.m. - 11:00 p.m.",
        "Notes": "Please call (718) 720-1010 before heading to the rink. For skating school information, please call (718) 390-7245. Persons under 18 years of age must have written consent form signed by parent or guardian. Agreement forms available at rink. A parent must sign the agreement form in the presence of a rink employee or parent's signature must be notarized."
      },
      {
        "Prop_ID": "Q099",
        "Name": "World Ice Arena",
        "Location": "Avery Avenue and 131 Street",
        "Phone": "(718) 760-9001 or (718) 760-9005",
        "Accessible": "Y",
        "lat": "40.7527",
        "lon": "-73.835",
        "IceSkating_Type": "Indoor",
        "Public_Skate_Admission_Price_Adult": "$6.00 weekdays; $9.00 weekends (starting Friday 7 p.m.); $9 holidays",
        "Public_Skate_Admission_Price_Child": "$6.00 weekdays; $9.00 weekends (starting Friday 7 p.m.); $9 holidays",
        "Public_Skate_Admission_Price_Senior": "$6.00 weekdays; $6.00 weekends (starting Friday 7 p.m.); $6 holidays",
        "Skate_Rental_Cost": "$5.50/person. You must wear socks to rent skates.",
        "Locker_Information": "Coin-operated lockers are available for rent ($0.75 per use).",
        "Sunday_Public_Skating_Hours": "12:00 p.m.- 4:45 p.m.",
        "Monday_Public_Skating_Hours": "9:00 a.m.- 5:15 p.m.",
        "Tuesday_Public_Skating_Hours": "9:00 a.m.- 5:15 p.m.",
        "Wednesday_Public_Skating_Hours": "9:00 a.m.- 5:15 p.m.",
        "Thursday_Public_Skating_Hours": "9:00 a.m.- 5:15 p.m.",
        "Friday_Public_Skating_Hours": "9:00 a.m.- 5:15 p.m. & 7:00 p.m. - 9:50 p.m.",
        "Saturday_Public_Skating_Hours": "Noon - 4:45 p.m. & 8:00 p.m. - 9:50 p.m",
        "Holiday_Public_Skating_Hours": "For holiday public skating hours, please visit <a href=\"http://www.worldice.com/\">worldice.com</a> for more information.",
        "Programming": "Please see the <a href=\"http://www.worldice.com\">World Ice Arena</a> website for details on Learn to Skate, hockey, and freestyle skate programming.",
        "Notes": "World Ice Arena is a year-round ice skating rink. The facility is Sled Hockey Accessible."
      }
    ]
  }
